name: 'Update README'

on:
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

jobs:
  recent-activity:
    name: 'Update README with latest activity'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/Checkout@v3
      - name: 'Update README.md from TEMPLATE.md'
        uses: Readme-Workflows/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CONFIG_FILE: 'sample.yml'
  metrics:
    name: 'Update SVGs for Readme stats'
    runs-on: ubuntu-latest
    needs: recent-activity
    steps:
      - uses: lowlighter/metrics@v3.33
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: neshvig10
          repo: neshvig10
          template: markdown
          filename: README.md
          
          base: ""
          
          config_octicon: yes
          
          plugin_stargazers: yes
          plugin_contributors: yes
